import os
import time
from collections import defaultdict, deque
from typing import Any
from uuid import UUID

import httpx
import jwt
from fastapi import FastAPI, HTTPException, Request, status
from pydantic import BaseModel, Field

from .chat_history import (
    append_exchange,
    create_conversation,
    delete_conversation,
    ensure_conversation,
    get_conversation_messages,
    initialize_chat_history,
    list_conversations,
)


# =============================================================================
# Configuration
# =============================================================================

# Internal ApexTrainer endpoint used to verify the user's existing login session.
# The browser never sends a trusted user ID directly to the AI Gateway.
# Instead, the Gateway forwards the login cookie to the ApexTrainer backend
# and asks the backend to identify the currently authenticated user.
AUTH_VERIFY_URL = os.getenv(
    "AUTH_VERIFY_URL",
    "http://apextrainer-server:3010/api/identity/user",
)

# Langflow flow endpoint used by the production ApexTrainer chat.
LANGFLOW_RUN_URL = os.getenv(
    "LANGFLOW_RUN_URL",
    (
        "http://apextrainer-langflow:7860/"
        "api/v1/run/apextrainer-chatbot?stream=false"
    ),
)

# API key used only to authenticate the AI Gateway itself to Langflow.
# This is NOT the user's MCP credential.
LANGFLOW_API_KEY = os.getenv(
    "LANGFLOW_API_KEY",
    "",
).strip()

# ID of the Langflow custom component that receives trusted user/session context.
LANGFLOW_COMPONENT_ID = os.getenv(
    "LANGFLOW_COMPONENT_ID",
    "CustomComponent-M3tu3",
)

# Maximum time the AI Gateway waits for Langflow to return a response.
LANGFLOW_TIMEOUT_SECONDS = float(
    os.getenv(
        "LANGFLOW_TIMEOUT_SECONDS",
        "120",
    )
)

# Simple per-user rate limit for the chatbot.
RATE_LIMIT_PER_MINUTE = int(
    os.getenv(
        "RATE_LIMIT_PER_MINUTE",
        "20",
    )
)


# =============================================================================
# MCP per-user authentication configuration
# =============================================================================

# Shared signing secret known only by:
#   1. ApexTrainer AI Gateway
#   2. ApexTrainer MCP server
#
# The secret itself is NEVER sent to Langflow.
# Langflow receives only a short-lived signed JWT.
MCP_GATEWAY_JWT_SECRET = os.getenv(
    "MCP_GATEWAY_JWT_SECRET",
    "",
).strip()

# Short lifetime reduces the impact if a token is ever exposed.
# Default: 300 seconds = 5 minutes.
MCP_GATEWAY_JWT_TTL_SECONDS = int(
    os.getenv(
        "MCP_GATEWAY_JWT_TTL_SECONDS",
        "300",
    )
)

# Issuer and audience are checked by the MCP server.
# These values help prevent the token from being accepted by another service.
MCP_GATEWAY_JWT_ISSUER = "apextrainer-ai-gateway"
MCP_GATEWAY_JWT_AUDIENCE = "apextrainer-mcp"


# =============================================================================
# FastAPI application
# =============================================================================

app = FastAPI(
    title="ApexTrainer AI Gateway",
    docs_url=None,
    redoc_url=None,
    openapi_url=None,
)


@app.on_event("startup")
async def initialize_gateway_database() -> None:
    """
    Create the AI chat-history tables when the Gateway starts.

    CREATE TABLE IF NOT EXISTS makes this safe to run repeatedly.
    """

    await initialize_chat_history()


# =============================================================================
# Request / response models
# =============================================================================

class ChatRequest(BaseModel):
    # Limit chat input size to reduce abuse and unexpectedly large requests.
    message: str = Field(
        min_length=1,
        max_length=2000,
    )

    # Generated by the frontend and used only to group one conversation.
    conversation_id: UUID


class ChatResponse(BaseModel):
    answer: str
    conversation_id: UUID


# =============================================================================
# In-memory per-user rate limiting
# =============================================================================

request_history: dict[str, deque[float]] = defaultdict(
    deque
)


def enforce_rate_limit(user_id: str) -> None:
    """
    Apply a simple sliding one-minute rate limit per authenticated user.

    This prevents one authenticated user from flooding the AI endpoint.
    """

    now = time.monotonic()
    window_start = now - 60

    history = request_history[user_id]

    # Remove requests that are older than the current one-minute window.
    while history and history[0] < window_start:
        history.popleft()

    if len(history) >= RATE_LIMIT_PER_MINUTE:
        raise HTTPException(
            status_code=status.HTTP_429_TOO_MANY_REQUESTS,
            detail=(
                "Too many AI requests. "
                "Please wait and try again."
            ),
        )

    history.append(now)


# =============================================================================
# ApexTrainer identity handling
# =============================================================================

def find_active_user_id(data: Any) -> str | None:
    """
    Extract the active authenticated user ID from common response formats
    returned by the ApexTrainer identity endpoint.

    The function supports several possible API response shapes so that the
    Gateway remains compatible with small backend response changes.
    """

    if not isinstance(data, dict):
        return None

    active_user_id = data.get("activeUserId")

    if active_user_id:
        return str(active_user_id)

    user = data.get("user")

    if isinstance(user, dict) and user.get("id"):
        return str(user["id"])

    nested_data = data.get("data")

    if isinstance(nested_data, dict):
        active_user_id = nested_data.get(
            "activeUserId"
        )

        if active_user_id:
            return str(active_user_id)

        nested_user = nested_data.get("user")

        if (
            isinstance(nested_user, dict)
            and nested_user.get("id")
        ):
            return str(nested_user["id"])

    return None


async def get_verified_user_id(
    request: Request,
) -> str:
    """
    Verify the existing ApexTrainer browser session.

    Security principle:
    The frontend is NOT allowed to decide which user ID the AI should use.

    Instead:
        Browser cookie
            -> AI Gateway
            -> ApexTrainer backend
            -> authenticated user ID

    This prevents a user from manually changing a user ID in the chat request
    and accessing another user's fitness information.
    """

    cookie = request.headers.get(
        "cookie",
        "",
    ).strip()

    if not cookie:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Authentication required.",
        )

    # Forward only the headers required for session verification.
    forwarded_headers = {
        "Cookie": cookie,
        "Accept": "application/json",
    }

    user_agent = request.headers.get(
        "user-agent"
    )

    if user_agent:
        forwarded_headers["User-Agent"] = user_agent

    origin = request.headers.get("origin")

    if origin:
        forwarded_headers["Origin"] = origin

    try:
        async with httpx.AsyncClient(
            timeout=httpx.Timeout(10.0),
        ) as client:
            response = await client.get(
                AUTH_VERIFY_URL,
                headers=forwarded_headers,
            )

    except httpx.RequestError as error:
        print(
            "[Auth] Backend connection error:",
            repr(error),
        )

        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=(
                "Authentication service is "
                "currently unavailable."
            ),
        ) from error

    # Invalid or expired user login session.
    if response.status_code in (401, 403):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail=(
                "Your login session is invalid "
                "or expired."
            ),
        )

    if not response.is_success:
        print(
            "[Auth] Unexpected status:",
            response.status_code,
            response.text[:500],
        )

        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=(
                "Authentication verification failed."
            ),
        )

    try:
        identity_data = response.json()
    except ValueError as error:
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=(
                "Authentication service returned "
                "invalid data."
            ),
        ) from error

    user_id = find_active_user_id(
        identity_data
    )

    if not user_id:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail=(
                "No authenticated active user "
                "was found."
            ),
        )

    return user_id


# =============================================================================
# Short-lived MCP user token
# =============================================================================

def create_mcp_user_token(
    user_id: str,
) -> str:
    """
    Create a short-lived JWT representing the authenticated ApexTrainer user.

    Important:
    - The browser cannot create this token.
    - Langflow cannot create this token.
    - Only the trusted AI Gateway can sign it.
    - The MCP server verifies the signature before trusting the user ID.

    JWT claims:
        sub -> authenticated ApexTrainer user ID
        iss -> token issuer
        aud -> intended MCP service
        iat -> issued-at timestamp
        exp -> expiration timestamp
    """

    if not MCP_GATEWAY_JWT_SECRET:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=(
                "MCP user authentication "
                "is not configured."
            ),
        )

    now = int(time.time())

    payload = {
        # "sub" is the trusted authenticated ApexTrainer user ID.
        "sub": user_id,

        # Identifies who created the token.
        "iss": MCP_GATEWAY_JWT_ISSUER,

        # Restricts where the token is intended to be accepted.
        "aud": MCP_GATEWAY_JWT_AUDIENCE,

        # Token creation time.
        "iat": now,

        # Token expires shortly after creation.
        "exp": (
            now
            + MCP_GATEWAY_JWT_TTL_SECONDS
        ),
    }

    return jwt.encode(
        payload,
        MCP_GATEWAY_JWT_SECRET,
        algorithm="HS256",
    )


# =============================================================================
# Langflow response parsing
# =============================================================================

def get_nested_value(
    data: Any,
    path: tuple[Any, ...],
) -> Any:
    """
    Safely retrieve a value from a deeply nested Langflow response.
    """

    current = data

    for part in path:
        if isinstance(part, int):
            if (
                not isinstance(current, list)
                or part >= len(current)
            ):
                return None

            current = current[part]

        else:
            if not isinstance(current, dict):
                return None

            current = current.get(part)

        if current is None:
            return None

    return current


def extract_langflow_answer(
    data: Any,
) -> str:
    """
    Extract the assistant text from several Langflow response formats.

    Langflow responses can differ slightly depending on flow components and
    versions, so multiple supported paths are checked.
    """

    possible_paths = [
        (
            "outputs",
            0,
            "outputs",
            0,
            "results",
            "message",
            "text",
        ),
        (
            "outputs",
            0,
            "outputs",
            0,
            "results",
            "message",
            "data",
            "text",
        ),
        (
            "outputs",
            0,
            "outputs",
            0,
            "artifacts",
            "message",
        ),
        (
            "outputs",
            0,
            "outputs",
            0,
            "outputs",
            "message",
            "message",
            "text",
        ),
        ("message",),
        ("text",),
    ]

    for path in possible_paths:
        value = get_nested_value(
            data,
            path,
        )

        if (
            isinstance(value, str)
            and value.strip()
        ):
            return value.strip()

    return ""


# =============================================================================
# Health endpoint
# =============================================================================

@app.get("/health")
async def health() -> dict[str, str]:
    """
    Lightweight health endpoint used by Docker and operational checks.
    """

    return {
        "status": "ok",
        "service": "apextrainer-ai-gateway",
    }


# =============================================================================
# Authenticated chat-history endpoints
# =============================================================================

@app.get("/conversations")
async def get_conversations(
    request: Request,
):
    user_id = await get_verified_user_id(request)

    return {
        "conversations":
            await list_conversations(user_id)
    }


@app.post("/conversations")
async def new_conversation(
    request: Request,
):
    user_id = await get_verified_user_id(request)

    conversation = await create_conversation(
        user_id
    )

    return {
        "conversation": conversation
    }


@app.get(
    "/conversations/{conversation_id}/messages"
)
async def conversation_messages(
    conversation_id: UUID,
    request: Request,
):
    user_id = await get_verified_user_id(
        request
    )

    try:
        messages = (
            await get_conversation_messages(
                user_id,
                conversation_id,
            )
        )

    except PermissionError as error:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Conversation not found.",
        ) from error

    return {
        "conversation_id": conversation_id,
        "messages": messages,
    }


@app.delete(
    "/conversations/{conversation_id}"
)
async def remove_conversation(
    conversation_id: UUID,
    request: Request,
):
    user_id = await get_verified_user_id(
        request
    )

    deleted = await delete_conversation(
        user_id,
        conversation_id,
    )

    if not deleted:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Conversation not found.",
        )

    return {
        "deleted": True,
        "conversation_id": conversation_id,
    }


# =============================================================================
# Authenticated AI chat endpoint
# =============================================================================

@app.post(
    "/chat",
    response_model=ChatResponse,
)
async def chat(
    body: ChatRequest,
    request: Request,
) -> ChatResponse:
    """
    Main authenticated ApexTrainer AI chat endpoint.

    Request flow:

        Browser
          -> /api/ai/chat
          -> AI Gateway verifies Better Auth session
          -> Gateway determines trusted user ID
          -> Gateway creates short-lived MCP JWT
          -> Gateway sends user context + JWT to Langflow
          -> Langflow forwards JWT to ApexTrainer MCP
          -> MCP verifies JWT and uses its "sub" as the user ID
          -> MCP tools query only that user's data
    """

    if not LANGFLOW_API_KEY:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=(
                "AI Gateway is missing its "
                "Langflow API key."
            ),
        )

    message = body.message.strip()

    if not message:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="Message cannot be empty.",
        )

    # -------------------------------------------------------------------------
    # Step 1: Verify the user's real login session.
    # -------------------------------------------------------------------------

    verified_user_id = (
        await get_verified_user_id(request)
    )

    try:
        await ensure_conversation(
            verified_user_id,
            body.conversation_id,
            message,
        )
    except PermissionError as error:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Conversation access denied.",
        ) from error

    # -------------------------------------------------------------------------
    # Step 2: Apply rate limiting using the trusted authenticated user ID.
    # -------------------------------------------------------------------------

    enforce_rate_limit(
        verified_user_id
    )

    # -------------------------------------------------------------------------
    # Step 3: Build a trusted Langflow session ID.
    #
    # The session ID contains the verified user ID and frontend conversation ID.
    # This keeps conversation memory separated between users/conversations.
    # -------------------------------------------------------------------------

    langflow_session_id = (
        f"apextrainer:"
        f"{verified_user_id}:"
        f"{body.conversation_id}"
    )

    # -------------------------------------------------------------------------
    # Step 4: Create a short-lived MCP credential for THIS authenticated user.
    #
    # This replaces the security role previously played by a single static
    # production MCP API key.
    # -------------------------------------------------------------------------

    mcp_user_token = create_mcp_user_token(
        verified_user_id
    )

    # -------------------------------------------------------------------------
    # Step 5: Build the Langflow payload.
    #
    # The tweak provides user context to the custom Langflow component.
    # Important: this user ID is useful context, but MCP authorization must
    # still rely on the cryptographically signed JWT.
    # -------------------------------------------------------------------------

    langflow_payload = {
        "input_value": message,
        "input_type": "chat",
        "output_type": "chat",
        "session_id": langflow_session_id,

        "tweaks": {
            LANGFLOW_COMPONENT_ID: {
                "apextrainer_user_id": (
                    verified_user_id
                ),
                "langflow_session_id": (
                    langflow_session_id
                ),
            }
        },
    }

    try:
        async with httpx.AsyncClient(
            timeout=httpx.Timeout(
                LANGFLOW_TIMEOUT_SECONDS,
                connect=10.0,
            ),
        ) as client:

            response = await client.post(
                LANGFLOW_RUN_URL,

                headers={
                    # Langflow API request format.
                    "Content-Type": (
                        "application/json"
                    ),

                    # Authenticates this Gateway to Langflow.
                    "x-api-key": (
                        LANGFLOW_API_KEY
                    ),

                    # ---------------------------------------------------------
                    # Request-scoped Langflow global variable.
                    #
                    # Langflow makes MCP_USER_TOKEN available only while this
                    # particular flow request is executing.
                    #
                    # In the Langflow MCP server configuration, the value of
                    # the Authorization header will reference MCP_USER_TOKEN.
                    #
                    # The value already includes the "Bearer " prefix.
                    # ---------------------------------------------------------
                    "X-LANGFLOW-GLOBAL-VAR-MCP_USER_TOKEN": (
                        f"Bearer {mcp_user_token}"
                    ),
                },

                json=langflow_payload,
            )

    except httpx.TimeoutException as error:
        raise HTTPException(
            status_code=status.HTTP_504_GATEWAY_TIMEOUT,
            detail=(
                "The AI service took too long "
                "to respond."
            ),
        ) from error

    except httpx.RequestError as error:
        print(
            "[Langflow] Connection error:",
            repr(error),
        )

        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=(
                "The AI service is currently "
                "unavailable."
            ),
        ) from error

    if not response.is_success:
        print(
            "[Langflow] Error:",
            response.status_code,
            response.text[:1000],
        )

        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=(
                "The AI service returned an error."
            ),
        )

    try:
        langflow_data = response.json()

    except ValueError as error:
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=(
                "The AI service returned "
                "invalid data."
            ),
        ) from error

    answer = extract_langflow_answer(
        langflow_data
    )

    if not answer:
        print(
            "[Langflow] No readable answer:",
            str(langflow_data)[:1000],
        )

        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=(
                "The AI service returned "
                "no readable answer."
            ),
        )

    try:
        await append_exchange(
            verified_user_id,
            body.conversation_id,
            message,
            answer,
        )
    except PermissionError as error:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Conversation access denied.",
        ) from error

    return ChatResponse(
        answer=answer,
        conversation_id=body.conversation_id,
    )
